events {}

http {
    upstream auth_upstream {
        server sandbox-auth-service:4101;
    }
    upstream payment_upstream {
        server sandbox-payment-service:4102;
    }
    upstream notify_upstream {
        server sandbox-notification-service:4103;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth_upstream/;
        }

        location /payment/ {
            proxy_pass http://payment_upstream/;
        }

        location /notify/ {
            proxy_pass http://notify_upstream/;
        }
    }
}

